//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Email.Templates.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Email.Templates.Notification
        ///
        ///&lt;p&gt;
        ///    Dear @Model[&quot;firstName&quot;] @Model[&quot;lastName&quot;],
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Congratulations! You’re just a few steps away from activating your account.
        ///    Click the link below to confirm your email address.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;a href=&quot;@Model[&quot;emailConfirmationLink&quot;]&quot; target=&quot;_blank&quot;&gt;
        ///        Verify my account
        ///    &lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot;&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Simple Transactional Email&lt;/title&gt;
        ///    &lt;style&gt;
        ///
        ///        @@media only screen and (max-width: 620px) {
        ///            table[class=body] h1 {
        ///                font-size: 28px !important;
        ///                margin-bottom: 10px !important;
        ///            }
        ///
        ///            table[class=body] p,
        ///            table[class=body] ul,
        ///            tab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model Email.Templates.Notification
        ///
        ///&lt;p&gt;
        ///    Dear @Model[&quot;firstName&quot;] @Model[&quot;lastName&quot;],
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Your user name is @Model[&quot;userName&quot;]
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    We have received a password reset request for the account associated with this email.
        ///    If you made this request, please click the link below to reset your password.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;a href=&quot;@Model[&quot;recoverPasswordLink&quot;]&quot; target=&quot;_blank&quot;&gt;
        ///        Click here to reset your password
        ///    &lt;/a&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
    }
}
