//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificate.Templates.App_LocalResources.LetterOfAttendance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Certificate.Templates.App_LocalResources.LetterOfAttendance.local", typeof(local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&apos;css/style.css&apos; rel=&apos;stylesheet&apos; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;wrapper&quot;&gt;
        ///        &lt;header&gt;
        ///            &lt;h1&gt;Critical Dose drug considerations&lt;/h1&gt;
        ///            &lt;h3&gt;for Post-Transplant Patients&lt;/h3&gt;
        ///        &lt;/header&gt;
        ///
        ///        &lt;main&gt;
        ///            &lt;h2&gt;Letter of Attendance&lt;/h2&gt;
        ///
        ///            &lt;div class=&quot;info&quot;&gt;
        ///                &lt;div class=&quot;left&quot;&gt;
        ///                    &lt;div class=&quot;underlined&quot;&gt;&lt;accountFullN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face {
        ///    font-family: сalibri;
        ///    src: url(&apos;data:font/truetype;charset=utf-8;base64,AAEAAAAVAQAABABQRFNJR68djRoABUaIAAAbWEVCRFQxOa4XAAQb6AAAT5xFQkxDfDVvAAAEa4QAABXgR0RFRgAmBGYABIFkAAAAHkdQT1NBxCNUAASBhAAArOJHU1VC8tALsQAFLmgAABggT1MvMmxocrgAAAHYAAAAYGNtYXByRtvZAAATvAAACORjdnQgr5O3+QAAScgAAAUKZnBnbfb2TQwAABygAAAJGmdhc3AAHAAjAAQb2AAAABBnbHlmSKzgogAAYFwAAmGYaGVhZOInFUAAAAFcAAAANmhoZWENrgs8AAABlAAAACRobXR4LWXg6AAAAjgAABGEa2VybnHfjMsAAsH0AAFLqmxvY2EE0SjcAABO1AAAEYhtYXhwKAEDDQAAAbgAAAAgbmFtZSZkUe4ABA2gA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
