//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificate.Templates.CertificateTemplates.LetterOfAttendance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Certificate.Templates.CertificateTemplates.LetterOfAttendance.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&apos;css/style.css&apos; rel=&apos;stylesheet&apos; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;wrapper&quot;&gt;
        ///        &lt;header&gt;
        ///            &lt;h1&gt;
        ///                Critical Dose drug considerations
        ///            &lt;/h1&gt;
        ///            &lt;h3&gt;for Post-Transplant Patients&lt;/h3&gt;
        ///        &lt;/header&gt;
        ///    &lt;/div&gt;
        ///    &lt;footer class=&quot;footer&quot;&gt;&lt;/footer&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&apos;css/style.css&apos; rel=&apos;stylesheet&apos; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;wrapper&quot;&gt;
        ///        &lt;header&gt;
        ///            &lt;h1&gt;
        ///                Critical Dose drug considerations
        ///            &lt;/h1&gt;
        ///            &lt;h3&gt;for Post-Transplant Patients&lt;/h3&gt;
        ///        &lt;/header&gt;
        ///    &lt;/div&gt;
        ///    &lt;footer class=&quot;footer&quot;&gt;&lt;/footer&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face {
        ///    font-family: nevis;
        ///    src: url(&apos;data:font/truetype;charset=utf-8;base64,AAEAAAAMAIAAAwBAT1MvMkEluHAAAAFIAAAAVmNtYXCa+7t1AAADbAAAAuZnYXNw//8AAwAAL7wAAAAIZ2x5Zg0etIwAAAc8AAAhqGhlYWTt2DRcAAAAzAAAADZoaGVhDsQGkQAAAQQAAAAkaG10eAloIsUAAAGgAAABzGtlcm4ALgASAAAo5AAAABhsb2Nh6EvwKgAABlQAAADobWF4cAB5AEYAAAEoAAAAIG5hbWWlIsEVAAAo/AAABa1wb3N0gp2GPAAALqwAAAENAAEAAAABAADS4VUrXw889QALCAAAAAAAw2fAVgAAAADEESlN/0D+UggAB2wAAQAGAAEAAAAAAAAAAQAABz7+TgBDCI3/QP9CCAAAAQAAAAAAAAAAAAAAAAAAAHMAAQAAAHMARgAFAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
